#!/bin/bash

jb | grep jbjb | awk '{print "scancel " $1}' > jobs.cancel && bash jobs.cancel

source /mnt/rna/home/programs/amber22/amber.sh
source /mnt/rna/home/programs/amber22/amber22_athene.sh

srun --pty -N 1 -n 10 --exclusive -p longq7-rna -u bash -i

for i in {50..76}; do    ls -l md_$i.mdcrd; done

#infinity
while :; do jb | grep testhGAA | awk '{print "scancel " $1}' > jobs.cancel && bash jobs.cancel; done

#check Tempatarures 
grep "NSTEP = 10000000" md_*.out | awk '{if ($10>100) print $0 }' | awk '{split($1,a,"."); split(a[1],b,"_"); print b[2]"\t" $10}' | sort -nk1,1

#jb work paths
jb | grep clus_con | awk '{system("scontrol show job " $1)}' | grep WorkDir

exclude these A100 nodes
#SBATCH --exclude=nodeamd[039-041],nodegpu[002-003]

#rsync

nohup rsync -chavzP --stats /mnt/rna/home/project_tetraloop_mbondi3/* /mnt/rna/home/nkumarachchi2019/scratch/project_tetraloop_mbondi3/ > nohup3.out &

#check progress of submitted md_1.outs 

jb | grep R |  awk '{ print("ssh "$8" \"tail -n 5 /tmp/nkumarachchi2019/"$1"/min.out\"\n"); system("scontrol show job "$1" | grep WorkDir \n"); system("ssh "$8" \"tail -n 8 /tmp/nkumarachchi2019/"$1"/min.out\"")}' 



check folders are working and get top folder in with NOT

jb | awk '{system("scontrol show job "$1)}' | grep WorkDir | awk '{split($1,a,"/"); printf("-not -name \""a[8]"\" ")}'


### check sim correct ##

printf "$( ls -ltr md_*.mdcrd | awk '{print$5}' | uniq)   $(ls -ltr md_*.rst | awk '{print$5}' | uniq)    $(ls -ltr md_*.out | awk '{print$5}' | uniq) \n"


awk '{if($2>=2.5 && $2<=3.0) printf($1",")}' rmsd1.dat 

source /mnt/rna/home/programs/amber22/amber.sh
ource /mnt/rna/home/programs/amber22/amber22_athene.sh

conda activate intelpy-env

# vemd render
render Tachyon vmdscene.dat /usr/local/lib/vmd/tachyon_LINUXAMD64 -aasamples 36 -res 2000 2000 %s -format TARGA -o %s.tga convert vmdscene.dat.tga a.png

#this line works in tcl so copy paste all
# vmd convert
convert vmdscene.dat.tga pic.png


#p y thon -m ipykernel install --user --name intelpy-env --display-name "intelpy"


jupyter nbconvert --ExecutePreprocessor.timeout=-1 --to notebook --execute plotter_*.ipynb

ls -l md_*.mdcrd | awk '{split($9,a,"."); split(a[1],b,"_"); print b[2]"\t"$NF}'  | sort -k1,1n | awk 'BEGIN{print "parm prmtop.new"}{print "trajin "$2}END{print "dihedral chi :1@O4'\'' :1@C1'\'' :1@N9 :1@C6"}'  > ptraj_chi_check.in


cpptraj -p strip.prmtop.new -y combined_md.mdcrd -tl

get min of a data set (P chi E here)
cat E_QM-MM_zero_1296.dat | awk '{if($2==200) print $1 "   " $3}' | sort -nk2,2  | awk '{s++; if(s==1)(min=$2); print $1"   "$2-min}' | sort -nk1,1


ls -l r_samp_1[0-3]/md_*.mdcrd > tmp
cat tmp | awk '{if($5!=15520480) print $0}'



