#!/bin/bash
#to find unproper minimezed, 
cat E_MM_zero.dat | sort -nk3,3 |  tail -10 

copy prmtop.zeroed.new to here from 2d_minimiezed. 

ls -l 2d_*/*/filelines_end  | awk '{split ($9,a,"/"); \
k="cp /mnt/rna/home/nkumarachchi2019/scratch/2d_minimized/"a[1]"/"a[2]"/prmtop.zeroed /mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_c1c2/"a[1]"/"a[2]"/"  ; system(k) }'


 ls -l 2d_*/*/test.pdb | awk '{split ($9,a,"/"); k="cp -r 2d_AA/BB5_RA3/gnuplot "a[1]"/"a[2]; print(k)}'
cp -r 2d_AA/BB5_RA3/gnuplot 2d_AA/BB5_RA3
cp -r 2d_AA/BB5_RA3/gnuplot 2d_AA/RA5_BB3
cp -r 2d_AA/BB5_RA3/gnuplot 2d_CC/BB5_RC3
cp -r 2d_AA/BB5_RA3/gnuplot 2d_CC/RC5_BB3
cp -r 2d_AA/BB5_RA3/gnuplot 2d_GG/BB5_RG3
cp -r 2d_AA/BB5_RA3/gnuplot 2d_GG/RG5_BB3
cp -r 2d_AA/BB5_RA3/gnuplot 2d_UU/BB5_RU3
cp -r 2d_AA/BB5_RA3/gnuplot 2d_UU/RU5_BB3
copy parmtop.zeroed from ~/scrach/prmtop.zeroed prmtop.zeroed.new to here
ls -l 2d_*/*/filelines_end  | awk '{split ($9,a,"/"); \
k="cp /mnt/rna/home/nkumarachchi2019/scratch/2d_minimized/"a[1]"/"a[2]"/prmtop.zeroed /mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_c1c2/"a[1]"/"a[2]"/"  ; system(k) }'



ls -l 2d_*/*/test.pdb | awk '{split ($9,a,"/"); k="cp -r 2d_AA/BB5_RA3/gnuplot/gnuplot.gp "a[1]"/"a[2]"/gnuplot/"; print(k)}'
cp -r 2d_AA/BB5_RA3/gnuplot/gnuplot.gp 2d_AA/BB5_RA3/gnuplot/
cp -r 2d_AA/BB5_RA3/gnuplot/gnuplot.gp 2d_AA/RA5_BB3/gnuplot/
cp -r 2d_AA/BB5_RA3/gnuplot/gnuplot.gp 2d_CC/BB5_RC3/gnuplot/
cp -r 2d_AA/BB5_RA3/gnuplot/gnuplot.gp 2d_CC/RC5_BB3/gnuplot/
cp -r 2d_AA/BB5_RA3/gnuplot/gnuplot.gp 2d_GG/BB5_RG3/gnuplot/
cp -r 2d_AA/BB5_RA3/gnuplot/gnuplot.gp 2d_GG/RG5_BB3/gnuplot/
cp -r 2d_AA/BB5_RA3/gnuplot/gnuplot.gp 2d_UU/BB5_RU3/gnuplot/
cp -r 2d_AA/BB5_RA3/gnuplot/gnuplot.gp 2d_UU/RU5_BB3/gnuplot/



ls -l 2d_*/*/test.pdb | awk '{split ($9,a,"/"); k="scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_c1c2/"a[1]"/"a[2]"/*.dat ./"a[1]"/"a[2]"/gnuplot/" ; print(k)}'

scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_10K/2d_AA/BB5_RA3/*.dat ./2d_AA/BB5_RA3/gnuplot/
scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_10K/2d_AA/RA5_BB3/*.dat ./2d_AA/RA5_BB3/gnuplot/
scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_10K/2d_CC/BB5_RC3/*.dat ./2d_CC/BB5_RC3/gnuplot/
scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_10K/2d_CC/RC5_BB3/*.dat ./2d_CC/RC5_BB3/gnuplot/
scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_10K/2d_GG/BB5_RG3/*.dat ./2d_GG/BB5_RG3/gnuplot/
scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_10K/2d_GG/RG5_BB3/*.dat ./2d_GG/RG5_BB3/gnuplot/
scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_10K/2d_UU/BB5_RU3/*.dat ./2d_UU/BB5_RU3/gnuplot/
scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_10K/2d_UU/RU5_BB3/*.dat ./2d_UU/RU5_BB3/gnuplot/

ls -l 2d_*/*/test.pdb | awk '{split ($9,a,"/"); k="scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_c1c2/"a[1]"/"a[2]"/alfa_gamma_all_in_one/*.pdb ./optimized_pdbs/" ; print(k)}'

scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_c1c2/2d_AA/BB5_RA3/alfa_gamma_all_in_one/*.pdb ./optimized_pdbs/
scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_c1c2/2d_AA/RA5_BB3/alfa_gamma_all_in_one/*.pdb ./optimized_pdbs/
scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_c1c2/2d_CC/BB5_RC3/alfa_gamma_all_in_one/*.pdb ./optimized_pdbs/
scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_c1c2/2d_CC/RC5_BB3/alfa_gamma_all_in_one/*.pdb ./optimized_pdbs/
scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_c1c2/2d_GG/BB5_RG3/alfa_gamma_all_in_one/*.pdb ./optimized_pdbs/
scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_c1c2/2d_GG/RG5_BB3/alfa_gamma_all_in_one/*.pdb ./optimized_pdbs/
scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_c1c2/2d_UU/BB5_RU3/alfa_gamma_all_in_one/*.pdb ./optimized_pdbs/
scp nkumarachchi2019@koko-login.hpc.fau.edu:/mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_c1c2/2d_UU/RU5_BB3/alfa_gamma_all_in_one/*.pdb ./optimized_pdbs/


ls -l 2d_??/*/alfa_gamma_all_in_one/*/opt.xyz | awk '{split($9,a,"/"); print a[1]"/"a[2]"/"a[3]"/"a[4]}' > all_paths


cat all_paths | awk '{print("cd "$1 "; perl /mnt/rna/home/nkumarachchi2019/scratch/2d_minimized_10K/scripts3_2d/create_init_md.pl; cd ../../../../")}'

#extract combine pbds
ls -l *.g_120/min.pdb | awk '{split($9,a,"/");  split(a[1],b,"."); split(b[1],c,"_"); print c[2]"\t"$9}' | sort -nk1,1 | awk '{s++; print "MODEL "s; system("cat "$2" | grep ATOM"); print "ENDMDL"}' > tmp1.pdb
ls -l ./a_*.g_120/test.pdb | awk '{split($9,a,"/"); split(a[2],b,"."); split(b[1],c,"_"); print c[2]"\t"$NF}' | sort -nk1,1  | awk '{s++; print "MODEL "s; system("cat "$2"|  grep HETATM");  print "ENDMDL"}'  >  all_pdb_rotation.pdb


cat all_paths | awk '{k="cd "$1"; sbatch ../../../../atlas.cpu.min.sh; cd ../../../../"; system(k)}'

jb | grep sand_min | awk '{print "scancel " $1}' > jobs.cancel && bash jobs.cancel

######################### 1D stuff ##############################################################



diff dimer_UA/rotation_alfa/angle_10/pes.com /home/nkumarachchi2019/dimeric_force_field/qm_calcs/dimer_UA/qm_hf_mp2_631g/rotation_alfa/angle_10/pes.com

###$$$$$$dont use these see bottom with  &&
##ls -l ./dimer_*/rotation_alfa/angle_*/pes.log  | wc 
##ls -d ./dimer_*/rotation_alfa/angle_10 | wc
##find . -print | grep -i opt.xyz > paths
##sed -i 's/..//' paths
##sed -i 's/alfa/alfa/g'
##cat paths
##cat paths | awk '{split($1,a,"/") ; k="cd "a[1]"; ../extract_single_structure.sh; cd .."; print k}'
##cat paths | awk '{split($1,a,"/") ; k="cd "a[1]"; ../extract_single_structure.sh; cd .."; s++; if(s%8==0) {print k ; system(k)}}'

cat  E_QM-MM_zero.txt | awk '{print($2)}' > QM-MM_notor.txt

sed -n '/FINAL RESULTS/,$p' */min2.out | grep "Torsion" */min2.out


ls -l ./angle_*/md.out | wc 

ls -l ./dimer_*/rotation_alfa/angle_*/opt.xyz | awk '{split($9,a,"/"); print($9)}' > all_paths && sed -i 's/..//' all_paths

ls -l ./dimer_*/rotation_alfa/angle_*/md.out | wc

ls -l ./dimer_*/rotation_alfa/E_MM_zero_??_alfa.txt | wc

sed -n '/FINAL RESULTS/,$p' */min2.out | grep "Torsion" */min2.out | wc

a=`pwd | awk '{split($1,a,"/") ; print (a[7])}'` 

dimer=`pwd | awk '{split($1,a,"/") ; print (a[7])}' | awk '{split($a[7],b,"_"); print (b[2])}'`

tor=`pwd | awk '{split($1,a,"/") ; print (a[8])}' | awk '{split($a[8],b,"_"); print (b[2])}'`

xmgrace ./dimer_C?/rotation_alfa/E_MM_zero_refpoint_zero_??_alfa.txt
xmgrace ./dimer_??/rotation_alfa/E_QM_refpoint_zero_??_alfa.txt

xmgrace ./dimer_??/rotation_alfa/E_QM_refpoint_zero_??_alfa.txt
xmgrace ./dimer_??/rotation_alfa/E_MM_zero_refpoint_zero_??_alfa.txt
xmgrace ./dimer_??/rotation_alfa/E_MM_zero_refpoint_zero_??_alfa.txt




ls -l ./dimer_CC/rotation_alfa/angle_*/md.out | awk '{s=split($9,a,"/"); split(a[s-1],b,"_"); \
 angle=b[2]; k="grep Etot "$9; l=""; k|getline l; close(k); print angle"\t"l}' | sort -nk1,1 > tmp.mm



# mv folders greater than 360 

ls -ltrd * | awk ' {split($9,a,"."); split(a[1],b,"_"); if(b[2]>360) {c=b[2]-360; print("mv "$9" z_"c"."a[2])} else {print ("mv "$9" "a[1]"."a[2])} }'

mv z_610.g_260 z_250.g_260
mv z_640.g_0 z_280.g_0
mv z_630.g_150 z_270.g_150
mv z_640.g_180 z_280.g_180


awk 'NR>1{$3=$2-p} {p=$2} 1'