#!/bin/csh -f

set sander = "mpirun -np 2 $AMBERHOME/bin/sander.MPI"
#set sander = "$AMBERHOME/bin/sander"

#initxyz="opt.xyz"
#prmtop="../../prmtop.zeroed.new"
ambpdb -aatm -p ./prmtop.zeroed.new -c opt.xyz > sample.pdb # creating a pdb from opt corrdinate

#this line create restrains using pes.log file as r1 r2 r4 r5 rk2 rk3
grep "^ D "  pes.*.log  | grep -v F  | awk '{l=" &rst           iat ="; for(i=2; i<=5; i++){l=l $i","}; \
 l=l"\n                r1 = "sprintf("%.1f", $6-180)", r2 = "sprintf("%.1f", $6)", r3 = "sprintf("%.1f", $6)", r4 = "sprintf("%.1f", $6+180)",\n                rk2 =   5000.0, rk3 =   5000.0, ialtd=0,               &end"; print l}'  > RST

/bin/rm -f min

cat > min <<EOF
Minimization with NMR restraints
 &cntrl
  imin=1,maxcyc=500000,ncyc=50000,ntb=0,cut= 999.0,
  nmropt=1,ntpr=50000,
 /
 &wt type='REST', istep1=0,istep2=0,value1=1.0,value2=1.0,
 /
 &wt type='END'
 /
LISTOUT=POUT
DISANG=./RST
EOF

cat > md.in <<EOF
0 step MD for alpha = 230 beta = 180 gamma = 230
 &cntrl
  imin=0,ntb=0,cut=999,nstlim=0,dt=0.001,nscm=5000,nrespa=2,ntt=3,gamma_ln=1,tempi=0,temp0=0,
 /
EOF

$sander -O -i min   -p ./prmtop.zeroed.new  -c opt.xyz -o min1.out -r min1.rst < /dev/null || goto error

$sander -O -i min   -p ./prmtop.zeroed.new -c min1.rst -o min2.out -r min2.rst < /dev/null || goto error

$sander -O -i md.in -p ./prmtop.zeroed.new -c min2.rst -o md.out   -r md.rst   < /dev/null || goto error

$AMBERHOME/bin/ambpdb -aatm -p ./prmtop.zeroed.new -c min2.rst > min.pdb

exit(0)
echo "  ${0}:  Program error"
exit(1)
